### ISSUE TITLE
How to send request with request method OPTIONS?

### ISSUE THREAD

**Issue by felikjunvianto** [loopj/android-async-http#1020]
Like the title suggest, how to send request with request method OPTIONS? After searching in Javadoc, I only found that the "The AsyncHttpClient can be used to make asynchronous GET, POST, PUT and DELETE HTTP requests in your Android applications."

AsyncHttpClient also don't have .options() method. Any workaround suggestion?

Thanks

**Comment by smarek** [comment]
Well there hasn't been OPTIONS request support since now, I've provided that in 9c7b6d41e3b84a5d62dfc914c29536708fc7dcdb

For lower versions than 1.4.9.1 (which is currently future release), you can do a subclass of AsyncHttpClient class and call protected method `sendRequest` with appropriate params yourself

**Comment by felikjunvianto** [comment]
Thanks for the information (and the include in newer version). It really helps :smile:
