### ISSUE TITLE
no retry when coming out of Airplane mode (UnknownHostException on first retry)

### ISSUE THREAD

**Issue by falkorichter** [loopj/android-async-http#713]
I have  an plain old AsynHttpCLient:

````
        asyncHttpClient.setUserAgent(platform.getUserAgentString());
        asyncHttpClient.setMaxConnections(2);
        asyncHttpClient.setTimeout(THIRTY_SECONDS);
        asyncHttpClient.setMaxRetriesAndTimeout(3, THIRTY_SECONDS);
````
We have a case where a bluetooth scan triggers a http request right after coming from Airplane mode. This request should be retried since the phone is just connecting to the WIFI again or to cellular.

It does not retry because of AsyncHttpRequest:184:

`````
            while (retry) {
                try {
                    makeRequest();
                    return;
                } catch (UnknownHostException e) {
                    // switching between WI-FI and mobile data networks can cause a retry which then results in an UnknownHostException
                    // while the WI-FI is initialising. The retry logic will be invoked here, if this is NOT the first retry
                    // (to assist in genuine cases of unknown host) which seems better than outright failure
                    cause = new IOException("UnknownHostException exception: " + e.getMessage());
                    retry = (executionCount > 0) && retryHandler.retryRequest(cause, ++executionCount, context);
````
This is not a "genuine unknown host case".

What was the intention behind this? How can I get the retries to work?

I tried to fork async-http just to test and play with the code, removing that specific (executionCount > 0) && did not help, since internally in the retryHandler Boolean b = (Boolean) context.getAttribute(ExecutionContext.HTTP_REQ_SENT); is null and it seems like the other code is not executed...

Thx alot

**Comment by smarek** [comment]
Important to know is that retry logic is handled by RetryHandler (custom RetryHandler implementation set to HttpClient), I've just fixed this problem in https://github.com/loopj/android-async-http/commit/2efb8dbfb9ca3d53dfc5626d5a6a54eb4913ef59

You can whitelist/blacklist exceptions (thus set if on caught request should be retried) calling `RetryHandler.addClassToWhitelist(Class<?> cls)` or `RetryHandler.addClassToBlacklist(Class<?> cls)`

**Comment by bradserbuddy** [comment]
I am testing retry, with the wi-fi turned off on my device (and\or the emulator). In that situation I only seem to receive UnknownHostExceptions, which aren't retried due to the (executionCount > 0) check in AsyncHttpRequest.makeRequestWithRetries(). The comment at the UnknownHostException catch mentions that it won't retry on the first UnknownHostException, but, since a new AsyncHttpRequest is made for each request, executionCount will always be 0 in my situation. I saw the commit aab00ac which removed the executionCount, but, that delta isn't in the current code. Is there a workaround for this? Am I missing something?
