### ISSUE TITLE
AsyncHttpClient onSuccess sometimes receives null String

### ISSUE THREAD

**Issue by ketan-jogani** [loopj/android-async-http#724]
```Java
AsyncHttpClient client = new AsyncHttpClient();
client.get(this,
                UrlConstants.URL_CAR_MODEL, constructParamsForCarModels(),
                new AsyncHttpResponseHandler() {
                    @Override
                    public void onSuccess(String content) {
                        super.onSuccess(content);
                        Log.d(TAG, "Success:" + content);
                        getCarModelResponse(content);
                    }
                    @Override
                    public void onFailure(Throwable error, String content) {
                        super.onFailure(error, content);
                        //Log.d(TAG, "Error : " + error);
                        Log.d(TAG, "failure:" + content);
                        fetchCarModelsFromServer();
                    }
                    @Override
                    public void onFinish() {

                    }
                });
```

From server I'm receiving a long string. But in onSuccess I get content as null.
The issue is not consistent. Also the issue is not from server side as I I have taken a TCP dump there.
Any help on this?

**Comment by miguelhughes** [comment]
Hi guys, I'm having a similar issue. im using 1.4.9. I'm attaching my code. As per your suggestion, I added all the handlers i found. 
When the error happens, my overload `public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable)` is called, and `responseString` is an empty string.
As the connection quality gets worse, the error becomes more frequent.
On strong normal connections (wi-fi) I hardly have any issues. In my emulator if I limit the speed to HSDPA, I get the issue once between 5 to 10 requests. if I limit the speed to UMTS, the issue happens on half the requests. the payload is about 1kbyte. 
Keep in mind that it happens loading the same url. 

Is it possible that some underlying library times out or drops the content because the data is just too slow?

I can PM you with the url I'm using if you need it. 

thanks for taking the time.
[OperationNewsTeasers.java.txt](https://github.com/loopj/android-async-http/files/330446/OperationNewsTeasers.java.txt)
