### ISSUE TITLE
using Apache HTTP 4.3

### ISSUE THREAD

**Issue by lucastan** [loopj/android-async-http#775]
According to this https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html

The HTTP lib in Android is frozen at 4.0 beta and most likely left to die in Android (it isn't updated in Lollipop).  Do you have any plans to move away from this?

**Comment by smarek** [comment]
Hello @lucastan, yes, in branch 1.5.0 we plan on go away from Android provided version of HttpClient and replace it with android port you linked.

I also don't plan to migrate from Apache HttpClient to HttpURLConnection (as Google advises) because there are already quite good libraries implementing that (such as OkHttp, Volley, etc..), and I don't intend to compete with them.

**Comment by panxw** [comment]
Great!

**Comment by smarek** [comment]
I call this achieved and closed, since with 1.4.9 we're fully migrated from Android provided `org.apache.http` classes to upstream version (currently 4.3.3), see the development in ticket #830
