### ISSUE TITLE
how to set contenttype to multipart/form-data

### ISSUE THREAD

**Issue by FinnSu** [loopj/android-async-http#800]
hello, my server's contenttype must be multipart/form-data,how to make contenttype be multipart/form-data, I don't know whether `params.put("avatar", mAvatarInputStream, "avatar", "multipart/form-data");` can work, please help me,thanks in advance.

**Comment by molavy** [comment]
i have same problem
django don't support application/x-www-form-urlencoded for file upload
on android 5 when i upload file it set content type as application/x-www-form-urlencoded
i don't have problem on android 4.2

**Comment by peitek** [comment]
Same problem here. If I'm trying to send a form without a file as `multipart/form-data`, it arrives on the server as `application/x-www-form-urlencoded` even though I set the header.

**Comment by sd6352051** [comment]
Same problem

**Comment by smarek** [comment]
What you are interested in is code placed in `RequestParams.java`

```java
public HttpEntity getEntity(ResponseHandlerInterface progressHandler) throws IOException {
        if (useJsonStreamer) {
            return createJsonStreamerEntity(progressHandler);
        } else if (streamParams.isEmpty() && fileParams.isEmpty()) {
            return createFormEntity();
        } else {
            return createMultipartEntity(progressHandler);
        }
    }
```

If RequestParams shouldn't be send as Json, it checks if there aren't streams or files, then it creates `application/x-www-form-urlencoded` through `UrlEncodedFormEntity`, otherwise it creates `multipart/form-data` through `SimpleMultipartEntity`

If you want to force `multipart/form-data`, use fix (now pushed to master https://github.com/loopj/android-async-http/commit/e8615d0) like this

```java
RequestParams rp = new RequestParams();
AsyncHttpClient ahc = new AsyncHttpClient();
rp.setForceMultipartEntityContentType(true);
ahc.post(url, rp, responseHandler);
```

**Comment by yanbober** [comment]
mark
