### ISSUE TITLE
HTTPPost priority

### ISSUE THREAD

**Issue by nikolakurtic** [loopj/android-async-http#810]
Is there a way to prioritize single HTTPPost?
I'm experiencing long delays while google maps is downloading maps live. Once, single lightweight HTTPPost took 7min to finish.

**Comment by smarek** [comment]
Hi, good question. The problem is in my opinion that Google Play Services library, does not use the same HttpClient (and probably uses HttpURLConnection) as the library does, so if it spams the network queue, the system gives out priority of which request will be managed first in order by time of request execution. 

You could probably delay Google Maps loading after you've set up your own requests.
Could you please put this question on stackoverflow.com ? I suspect this is problem not specific to android-async-http library, but to all libraries that provide network communication.

Also you could detect how long the request didn't come back, cancel it after some timeout period and push it again. 

Additional question, 7min request you observed was on which connectivity? Cell network (2G or 3G or LTE) or Wifi?

**Comment by nikolakurtic** [comment]
Thanks for answering!
I asked the same question on SO. I tried both 2G and 3G and similar happens. Works fine on wifi (as expected).

**Comment by smarek** [comment]
@nikolakurtic can you please link the question ? thanks

**Comment by nikolakurtic** [comment]
http://stackoverflow.com/questions/28811453/loopj-and-google-maps-in-the-same-time/28816235#28816235
