### ISSUE TITLE
use httpurlconnection replace of httpClient when the SDK version > 9? 

### ISSUE THREAD

**Issue by woshixhs** [loopj/android-async-http#827]
we can use httpurlconnection replace of httpClient when the SDK version > 9. why not?

**Comment by dkozel** [comment]
smarek has talked about why this library uses HttpClient rather than HttpURLConnection.

"I also don't plan to migrate from Apache HttpClient to HttpURLConnection (as Google advises) because there are already quite good libraries implementing that (such as OkHttp, Volley, etc..), and I don't intend to compete with them." -smarek
https://github.com/loopj/android-async-http/issues/775

**Comment by smarek** [comment]
@dkozel thank you for clarification, I'm closing this issue, as your response is correct.
