### ISSUE TITLE
New Android 5.1 Deprecated classes which could affect on the library in future

### ISSUE THREAD

**Issue by SlavVv** [loopj/android-async-http#830]
>The org.apache.http classes and the AndroidHttpClient class have been deprecated in Android 5.1.

This is from the new Android 5.1 APIs update. https://developer.android.com/about/versions/android-5.1.html#http

**Comment by panxw** [comment]
Maybe you could see android volley.

**Comment by dkozel** [comment]
smarek has said that the library will use a port of the Apache HttpClient for future releases as the version shipped with Android is frozen (and now deprecated) at 4.0 beta.
https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html

"in branch 1.5.0 we plan on go away from Android provided version of HttpClient and replace it with android port" -smarek https://github.com/loopj/android-async-http/issues/775

**Comment by smarek** [comment]
Thank you and yes, I'll be pushing 1.5.0 branch forward, so we won't fall into problems as those classes will be removed in future Android version.

**Comment by kjkrum** [comment]
Apache HTTP has been removed from the M preview: http://developer.android.com/preview/behavior-changes.html

**Comment by titanseason** [comment]
@kjkrum Android-async-http works well on Android M, I debuged this last week

**Comment by smarek** [comment]
@titanseason should not work, how come?

**Comment by kjkrum** [comment]
@titanseason What version?  Only the 1.5.x branch should work on M.  If an earlier version works, Google might have "removed" Apache HTTP by removing it from the Android SDK stub library, similar to the way they remove methods with the `@hide` annotation.  This would make sense, since it would prevent massive breakage of existing apps.  If this is how they handled it, future versions of android-async-http could be built against a stub library of Apache HTTP instead of incorporating the whole thing and bloating apps that use it.

**Comment by kjkrum** [comment]
(Though that would be a gamble, since Google might actually remove Apache HTTP at some point in the future.)

**Comment by titanseason** [comment]
@kimiyash 
I download Android M preview image for Nexus 5 at https://developer.android.com/preview/download.html, and update my Nexus 5 Device with the image.

Android-async-http (Version 1.4.6) works well on my Nexus 5

**Comment by kjkrum** [comment]
Then they must have only removed Apache HTTP from the stub library.  Version 1.4.x will continue to run, it just won't be compilable against M or later SDKs.

**Comment by LittlePanpc** [comment]
Will HttpClient be replaced by HttpUrlConnection or other alternative in android-async-http? I think this is a final solution.

**Comment by smarek** [comment]
Nope, we discussed this already, and there are already good libraries based on HttpUrlConnection, we're not going to implement that again. Version 1.5.0 (as soon as I get some time to push it forward) will be based on Apache HttpComponents 4.3+ (see https://github.com/loopj/android-async-http/issues/830#issuecomment-87715593 and #775)

**Comment by gmbett** [comment]
If you change your target sdk to Android M (API 23) then all deprecated classes related to HTTP client are no longer available and Android-async-http won't work.

You need to add "useLibrary 'org.apache.http.legacy'" in your gradle configuration.

**Comment by panxw** [comment]
![Ratios](http://www.199it.com/wp-content/uploads/2015/06/34dcd90da781ce6.jpg)

**Comment by smarek** [comment]
@gmbett good tip!
@panxw up to 5.1 (API22) everything works, it's API 23 Android Marshmallow (currently in preview) that' causing the troubles.

**Comment by hanbo** [comment]
There is a org.apache.http.legacy.jar in Android/Sdk/platforms/android-23/optional which can be used as a workaround for eclipse based projects.

**Comment by zhangchaoxu** [comment]
give a tip for someone just like me, do not know how to add "useLibrary 'org.apache.http.legacy'"
just follow [this](http://stackoverflow.com/questions/30856785/how-to-add-apache-http-api-legacy-as-compile-time-dependency-to-build-grade)

1.  upgrade the build gradle to lastest version in /build.gradle
`buildscript {
    ...
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
    }
}`

2.  and then add org.apache.http.legacy in module like app/build.gradle
`
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"
    useLibrary 'org.apache.http.legacy'
    ...
}
`

**Comment by zhangchaoxu** [comment]
wow, i am sorry to said that, there is still a compile issue said that  org.apache.http related class can not found, even after i added useLibrary 'org.apache.http.legacy' in my project's gradle configuration.
finally, i copied org.apache.http.legacy.jar from sdk/platforms/android-23/optional to libs folder of my module, and it works.

@gmbett , does `useLibrary 'org.apache.http.legacy'` works in your case, any other tips? Thanks

**Comment by TylerMcCraw** [comment]
@zhangchaoxu thanks for the tips on the workaround.

Hopefully, @smarek will be able to resolve this for 1.5.0. Granted, I'm sure it will take quite a bit of work to refactor it so that there are no dependencies on org.apache.http.Header. 
Thanks for helping out with this, @smarek!

**Comment by TylerMcCraw** [comment]
@zhangchaoxu, did you have to do anything to your project after copying org.apache.http.legacy.jar to your libs folder? My project still shows compilation issues after doing this.

**Comment by kjkrum** [comment]
> i copied org.apache.http.legacy.jar from sdk/platforms/android-23/optional to libs folder of my module, and it works.

Have you tested it on a device, or just compiled it?  My understanding is that `org.apache.http.legacy` is just a stub library, and if you compile it into your app it'll crash at runtime.

**Comment by zhangchaoxu** [comment]
@TylerMcCraw 
just add `compile fileTree(dir: 'libs', include: ['*.jar'])` or `compile files('libs/org.apache.http.legacy.jar')` into the dependencies of the module's build.gradle, and then sync it.

@kjkrum 
yes, i have tested in genymotion vm with 4.4 and 5.0/an old HTC mobile with Android 4.0/Nexus5 with Android5.0, all of above works well.
Maybe i need to test in Android 6.0 as well, thanks for your advise.

**Comment by zhangchaoxu** [comment]
@kjkrum 
already tested in Android6.0 with AVD, and it works well.

**Comment by gmbett** [comment]
@zhangchaoxu 
The flag useLibrary 'org.apache.http.legacy' mentioned in https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client, only allows you to compile your project (when compileSdkVersion is 23)

In my case after adding the mentioned flag, Android Studio was still complaining that some classes didn't exist, so at the end I decided to copy the org.apache.http.legacy.jar into the libs folder.

**Comment by zhangchaoxu** [comment]
@gmbett 
thanks, i just do the copy work as you mentioned, fortunately, it works well.

**Comment by smarek** [comment]
Compatibility change was pushed into **master** for 1.4.9-SNAPSHOT version, see commit 2f4d1d8ad4bb4a1f531a57487601668b3527758c

**Comment by djKooks** [comment]
In android document, it comments to define library on build.gradle to use apache library.

android {
    useLibrary 'org.apache.http.legacy'
}

Android suggest to use HttpURLConnection for alternative, and I wonder is there a plan or way to switch into on it.

**Comment by Griffins** [comment]
I thought someone assigned himself this issue.  Else we should try to port
this library to use HttpUrlConnection. I don't know a lot about http but am
willing to do some research and help.

**Comment by smarek** [comment]
@Griffins I'm assigned but I don't have the time to fix all this right now.
If you're willing to contribute and do some research, would be great to provide script to repackage production version of HttpClient-4.X, which is main issue we're solving right now.

There are good HttpUrlConnections based async http requesting libraries out there, but this one was and will be based on HttpClient, no need to do just another library like those.

We need to have JAR of Apache HttpClient components (all of them) but not under org.apache, as that would cause classpath conflicts, but under different namespace (such as `com.loopj.httpclient`)

Something like that was done previously, see HttpClientAndroidLib project (now unmaintained and deprecated) https://code.google.com/p/httpclientandroidlib/

More info on the topic, see:
https://issues.apache.org/jira/browse/HTTPCLIENT-1632
https://stackoverflow.com/questions/32178854/android-api-23-httpclient-4-x-repackaged

**Comment by Griffins** [comment]
I look at it tomorrow. Probably ill have an idea on wat to try after that.
Its 9pm here!

**Comment by kjkrum** [comment]
Again, this library CANNOT be ported to use `HttpUrlConnection` because it exposes its use of Apache HTTP through things like exceptions and method parameters.  A port could never be made backward-compatible.  It could be conceptually similar, but it would be a different library.

**Comment by smarek** [comment]
@Griffins so I have it working, see repository here:
https://github.com/smarek/httpclient-android/

Currently requesting artifact group and id on Sonatype Nexus repository, and I'll push updated android-async-http library with this as dependency, instead of HC teams repackaged version or `useLibrary` hack

**Comment by jeremylan** [comment]
@smarek Any idea on when the updated android-async-http library with this change will be released?

Thanks so much for all the help and work with this great library.

**Comment by smarek** [comment]
@jeremylan I should be able to do it through the weekend, there are changes needed to be done along using 4.3.3 upstream HttpClient, before the release is feasible.

**Comment by jeremylan** [comment]
@smarek Thanks heaps for the reply and all the work. All the best.

**Comment by TylerMcCraw** [comment]
Thanks @smarek!

**Comment by smarek** [comment]
So now we're officially running on stable upstream HttpClient 4.3.3 version, repackaged and published on Maven through group+artifact `cz.msebera.android:httpclient:4.3.3`, see the build script repository for reference https://github.com/smarek/httpclient-android

Code was updated to new dependency, and all tests run smoothly, compiled against latest Android SDK 23, see commit for reference 15f9556b578dbf247ff32032461b094d4bfd31a9

To convert your current code, simple solution is to use sed to replace `org.apache.http` links with `cz.msebera.android.httpclient`
Sample find+sed command is
```
find . -name '*.java' -exec gsed -i 's/org.apache.http/cz.msebera.android.httpclient/g' \{\} +
```

Sincerely we're not allowed to publish to maven under `org.apache` group prefix, and we cannot use `org.apache` group in published archives, because of possible clash of classpaths on Android systems, so this is the only downside with the current solution.

I've just uploaded new `1.4.9-SNAPSHOT` into staging repository, see https://oss.sonatype.org/content/repositories/snapshots/com/loopj/android/android-async-http/1.4.9-SNAPSHOT/
Read on how to add snapshot version to your project in [README.md](https://github.com/loopj/android-async-http/blob/master/README.md)

For those who'll be testing build from source, there is also fix to get correct javadocs generated on project, see a5399d839be665bfd7a0d408c7e9f5d4dafc7bd2 for reference

Please all of you, who watch this ticket, try this snapshot, and I'll solve some issues along the way on the 1.4.9 release, before publishing the non-SNAPSHOT version into central.

**Comment by jeremylan** [comment]
Hi @smarek I just tested the 1.4.9 snapshot with my code, compiled with API 23 and running in API 19 and API 23 emulators.

It all seems to work OK, thank you!

**Comment by smarek** [comment]
Cool, can anybody else please confirm this finds? Also I'd be greatful for tests done on API3-API10 (as we still declare the compatibility), if anybody is willing to do that.

**Comment by LaurieScheepers** [comment]
Used the 1.4.9 snapshot and replaced the necessary imports and can confirm it works

**Comment by Saren-Arterius** [comment]
same as @LaurieScheepers, it works.

**Comment by smarek** [comment]
Heads up, I've just released 1.4.9 to Maven Central repository, updated **master** branch with latest code, uploaded new javadocs, updated readmes with new version.

Also we're now sitting on top of HttpClent 4.3.6 ( https://github.com/smarek/httpclient-android/releases/v4.3.6 ), which already includes HttpClient-Cache and HttpMime libraries of same version, so you can drop the external dependencies, if you're using any. 

1.5.0 built on top of upstream 4.3+ (hopefully we'll manage to get to 4.4+ or even 4.5+) has a lot of issues to be solved, so I'd welcome any help on updating the library according to our options, now since we're not relying on Android provided HttpClient anymore.

1.4.9 will remain as LTS version, and I plan to upload minor revisions, however no big changes will get merged into 1.4.9.X versions

Thank you all for your contribution.

**Comment by LaurieScheepers** [comment]
@smarek awesome, I'll update to the new official version tomorrow. Thanks :+1:

**Comment by jeremylan** [comment]
Great work @smarek !!

**Comment by Zapnologica** [comment]
Thank you so much for 1.4.9 you saved my but and a whole lot of time.

**Comment by panxw** [comment]
I made one base on Android Volley,  no HttpClient(apache http) need now! 
https://github.com/panxw/android-volley-hurlstack

**Comment by LittlePanpc** [comment]
@panxw Bad idea to set Android API 14+

**Comment by panxw** [comment]
@LittlePanpc It's Android API 9+ ok!

**Comment by smarek** [comment]
@panxw good for you, closing for Off Topic discussion reasons
