### ISSUE TITLE
JsonHTTPResponseHandler onFailure is declared as final

### ISSUE THREAD

**Issue by efrainluna00** [loopj/android-async-http#853]
Hi, congrats for this great library, I have been using it and works really nice!

I just found something small, when you create a JsonHTTPResponseHandler and try to override the onFailure method like this:

```
 AsyncHttpClient client = new AsyncHttpClient();
        client.get("http://192.168.2.54:8080/login/register/doregister", params, new JsonHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONObject obj) {
                .
                .
                .
}
@Override
public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable e){
                                      .
                                      .
                                      .
} 
```
Fails because onFailure is declared as final method on the JSONHTTPResponseHandler class definition

**Comment by smarek** [comment]
Yes, in JsonHttpResponseHandler this method is declared final, as it serves response in callbacks

  - onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse)
  - onFailure(int statusCode, Header[] headers, Throwable throwable, JSONArray errorResponse)
  - onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable)

Sincerely, it has to be public because of inheritance of interface method. You should use non-final methods in the callback.
