### ISSUE TITLE
Parallel calls reusing the same headers

### ISSUE THREAD

**Issue by taher-mosbah** [loopj/android-async-http#865]
Hello,
I'm using an AsyncHttpClient instance in a WS manager (singleton) that I use for multiple calls and I'm adding custom headers used for authentication.
My issue is if I have 2 consecutive calls for 2 different WS with different headers the client seems to reuse the same headers.
PS : I tried to use removeAllHeaders but got the same results.

**Comment by smarek** [comment]
Can you please create a SSCCE (see the http://sscce.org/ ) for this issue? It's not the first time we hear about something similar, however it always turned out to be problem of developer usage.

Regarding the headers, there are two sets of them, first `addHeader`,`removeHeader`,`removeAllHeaders` on AsyncHttpClient, which is setting global set of Headers used for all requests done by the library instance.

Second are headers given as params to `.get(...)`, `.post(...)` and so on, those are not saved anywhere and are used only once.

If you know this and you're getting different behavior, please try and explain your situation a bit more.
Thanks
