### ISSUE TITLE
Improve user routing to this project

### ISSUE THREAD

**Issue by slandelle** [loopj/android-async-http#876]
Hi,

I run (inherited actually, project was originally founded by @jfarcand) a project with a very similar name: [AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client). AsyncHttpClient is older than both android-async-http and the HttpComponents async module that you wrap, so I think it honestly "owns" the name.

Due to your API being very similar to ours, some of your users get confused and end up creating issues on ours, and polluting our mailing list. As this happens quite frequently, it become a nuisance.

Would it be possible for you to improve the way you advertise how to get in touch with you for issues and help? Maybe improving your webpage or creating your own google group? I know that there are Github logos everywhere, but it doesn't seem to be enough...

Regards

**Comment by smarek** [comment]
Well, that's unfortunate, I too inherited from @loopj, don't know it the name is related or just coincidence. However do not assume anything about `owning name`, that's unnecessary silly talks. If that would come into question, you should really contact James Smith directly, I'm not eligible to make any statements about his copyright.

I've gone through your API, and it's really different, so in my opinion it isn't possible to confuse those two projects except for name and main class name. Anyway, how often does this happen? Is it once a week or more?

Also we don't do any Google Groups or mail support, just the plain ol' Github issues, so that's not something we could change our advertisement about, in fact it's your option to put a large banner over your GG to tell the users about possibility of mistaking the GG mailing with our issue tracker.

From what I see

  - We do not intend to extend our support channels with GG, so that will for now be your specifics
  - About advertisement:
    - http://loopj.com/android-async-http/#reporting-bugs-or-feature-requests
    - This is like the only official channel except for this github repository

So, if you come up with anything specific, regarding this possibly confusing situation, I'll be happy to consider it, but for now I don't see anything we could do to help you out. Feel free to reply

**Comment by slandelle** [comment]
> Well, that's unfortunate, I too inherited from @loopj, don't know it the name is related or just coincidence. However do not assume anything about owning name, that's unnecessary silly talks.

By `owning the name`, I'm not talking about copyright. I'm just stating that your project chose an unfortunate name (which I agree is very/too generic), and could have checked first.

> About advertisement:
http://loopj.com/android-async-http/#reporting-bugs-or-feature-requests

Yeah, exactly my point, you have to scroll all the way down to find this.
Users being lazy as they are, they instead google for `AsyncHttpClient`, which is the main class for both project, and arrive on our project, not yours. Hence my request to do a better job at advertising where your users should be asking for help, be it Github bug tracker, a mailing, SOF, or whatever.

Anyway, at least I now have this issue to redirect your users who get lost on my side.

**Comment by smarek** [comment]
Yes I do agree, about the presentation page, that isn't the reason why users use your GG instead of this GH issues. Simply querying "AsyncHttpClient Android" should be enough.

On the other hand, I don't see any CONTRIBUTION notes on your repository, that could help the users to  realize, they are not using channel for Android library but for Java library (indeed, this is too confusing)

If they get lost, I don't think it's good idea to redirect them to this issue, instead, if I were you, I'd use https://github.com/loopj/android-async-http/issues or http://loopj.com/android-async-http/#reporting-bugs-or-feature-requests links. However, that's just like my opinion man :)
