### ISSUE TITLE
Update Documentation for "onProgress"

### ISSUE THREAD

**Issue by JamesCullum** [loopj/android-async-http#897]
Just wasted a couple hours because its everywhere documented as (int,int) though its actually (long,long) since https://github.com/loopj/android-async-http/commit/f4db52c68a15c4c387f2a1781f1b9a788497a8b3.

**Comment by smarek** [comment]
Only place I've found the documentation being wrong is AsyncHttpResponseHandler javadoc, if you have more places, where the documentation is incorrect, please point out.

**Comment by JamesCullum** [comment]
Yeah, its like this in the javadoc, and also on [GitHub](https://github.com/loopj/android-async-http/issues/311) and [Stack OverFlow](http://stackoverflow.com/questions/20408253/loopj-get-progress-while-downloading-image-using-binaryhttpresponsehandler)

**Comment by JamesCullum** [comment]
Added answers there. The wrong definition is still [here](http://loopj.com/android-async-http/doc/com/loopj/android/http/AsyncHttpResponseHandler.html)

**Comment by smarek** [comment]
@JamesCullum thanks, I've fixed SO and GitHub responses, so it matches latest state of code, javadoc will be uploaded soon, sadly, online javadoc is for older version (1.4.6) so that needs fix for sure.

However, generally speaking, this shouldn't be the source of information you should be using, and even if you do, adding `@Override` annotation will trigger in common Java IDEs (Android Studio, Eclipse, ...) warning, that method doesn't match parent definition, and you should for sure check that your method overrides method from parent/interface, because how could it work, if you don't override one?

**Comment by smarek** [comment]
@JamesCullum so, http://loopj.com/android-async-http/ mainpage is updated for latest release 1.4.7 and docs (http://loopj.com/android-async-http/doc/) are updated also, however index.html is cached, so the mainpage will be updated with cache expiration, and subsequent pages are already available (ie. http://loopj.com/android-async-http/doc/com/loopj/android/http/AsyncHttpResponseHandler.html )
