### ISSUE TITLE
How to achieve breakpoint resume upload?

### ISSUE THREAD

**Issue by ruijun** [loopj/android-async-http#901]
Hi,
My server support breakpoint resume upload. How to achieve breakpoint resume upload in android-async-http?

**Comment by smarek** [comment]
This is currently not supported by library. And I don't see this being supported anywhere near. 
Compared to resuming downloads, you don't have option to use data range, etag, if-modified-since or other protocol supported way, only way would be to do checksum and length check on both sides and upload remaining of the file, or use some kind of "block pushing" loop (not pushing whole file, but uploading smaller parts and keeping track of final file checksum and pushed blocks), but that's not something this library should do.
