### ISSUE TITLE
Response cannot be parsed as JSON data

### ISSUE THREAD

**Issue by protectedd** [loopj/android-async-http#911]
I'm getting the `Response cannot be parsed as JSON data` error. 

My codes:
http://pastebin.com/Tj31cc1U

Log:
http://pastebin.com/eMKeZPCh

Thanks.

**Comment by smarek** [comment]
Well, did you take a look on what data is returned, if it is JSON?

**Comment by protectedd** [comment]
If you mean the website response, yes I looked. It returned what I need like this:
`[{"_name":"3","_surname":"4","_graduated_from":"5","_graduated_in":"6","_born_place":"7","_birthday":"8"}]` 

But in android studio logs there no information about JSON.

**Comment by smarek** [comment]
So from logs I can tell two things:

 - `onFailure(int, Header[], String, Throwable) was not overriden, but callback was received` log means, implement this callback method to get the String response so you can check the response is correct
 - You're expecting JSONObject (`onSuccess(int statusCode, Header[] headers, JSONObject responseBody)`) but the JSON you've showed here is `JSONArray`, so that should be why you're getting error

Also I really recommend you to use JSON deserialization library, such as Gson or JacksonJSON (FasterXML), because you'll need to do manually type checking and object parsing, which is unnecessary overhead. See the example of auto-deserialization with this library here:
https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/JsonSample.java#L63
