### ISSUE TITLE
Setting Asynchttpclient Cipher

### ISSUE THREAD

**Issue by wornwinter** [loopj/android-async-http#940]
Hi there,

I'm currently using android-async-http in a project and it's been great so far until I started using cloudflare. It's:

```error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:744 0xabbdbd74:0x00000000)```

I've been researching this and narrowed it down to the use of the wrong SSL cipher setting. Is there a way within android-async-http to easily change this? Or am I completely missing the mark?

**Comment by smarek** [comment]
This is problem of underlying LibSSL implementation, where you're trying to connect with unsupported version of SSL/TLS (eg. using TLSv1 on SSL3 only server)

You can test the backend using ssllabs.com/ssltest/analyze.html testing suite, which should show if the backend has problem with ciphering setting.

Library does not use different than system SSLSocketFactory (which is the cause), only if you use `(true, 80, 443)` constructor of AsyncHttpClient, it will try to enforce TLS, see code for reference
```java
public class MySSLSocketFactory extends SSLSocketFactory {
    final SSLContext sslContext = SSLContext.getInstance("TLS");
```

Otherwise it's using system default SSL settings.
You can provide your own `SchemeRegistry` instance to constructor of library, to provide different SSLSocketFactory with different SSL security settings.
