### ISSUE TITLE
Can't find  'cz.msebera.android.httpclient.HttpEntity'.

### ISSUE THREAD

**Issue by xuxiping2014** [loopj/android-async-http#968]
just see my pics.
1.
![Uploading QQ20150923150252.png…]()  .

2.
![Uploading QQ20150923150317.png…]()  .

**Comment by smarek** [comment]
Screenshots were not uploaded, try again

**Comment by xuxiping2014** [comment]
Sorry,pics are here.
![qq20150923150252](https://cloud.githubusercontent.com/assets/8576687/10065084/254dcaa2-62b3-11e5-88a9-775d9d13a61d.png)
![qq20150923150317](https://cloud.githubusercontent.com/assets/8576687/10065086/27b2e548-62b3-11e5-9c01-435b23c4a5b6.png)

**Comment by xuxiping2014** [comment]
So,where is cz.msebera.android.httpclient.httpEntity? i just can't find it.

**Comment by xuxiping2014** [comment]
My jar Version is "1.4.9".

**Comment by xuxiping2014** [comment]
anybody knows？

**Comment by smarek** [comment]
Since you're not using Maven dependency management

Look for JARs here: https://repo1.maven.org/maven2/cz/msebera/android/httpclient/
Correct version to add to libraries is what is listed in `build.gradle` in `library` project in `dependencies block`, in version of library: https://github.com/loopj/android-async-http/blob/1.4.9/library/build.gradle#L27

```groovy
dependencies {
    compile 'cz.msebera.android:httpclient:4.3.6'
}
```
Look for JAR of version 4.3.6
